openapi: 3.0.0
info:
    title: Palindrom-Checker
    version: 1.0.0

paths:
  # TODO: REST-Endpunkt spezifizieren

components:
  schemas:
    Ergebnis:
      type: object
      properties:
        eingabe:
          type: string
          description: Die normierte Eingabe (nur Kleinbuchstaben, Leerzeichen am Anfang/Ende entfernt)
        istPalindrom:
          type: boolean
          description: Gibt an, ob die Eingabe ein Wortpalindrom ist oder nicht
        nachricht:
          type: string
          description: Textnachricht, die das Ergebnis beschreibt
      required:
        - eingabe
        - nachricht
        - istPalindrom
    Fehler:
      type: object
      properties:
        nachricht:
          type: string
          description: Fehlermeldung
      required:
        - nachricht